
[general]
	#If the model should be rendered translucent
	modelTranslucency = true
	#An example boolean in the client config
	clientBoolean = true
	#The scale to render the model at
	#Range: 1.0E-4 ~ 100.0
	modelScale = 0.0625
	#An example list of Strings in the client config
	clientStringList = []
	#An example DyeColor enum in the client config
	#Allowed Values: WHITE, ORANGE, MAGENTA, LIGHT_BLUE, YELLOW, LIME, PINK, GRAY, LIGHT_GRAY, CYAN, PURPLE, BLUE, BROWN, GREEN, RED, BLACK
	clientDyeColorEnum = "WHITE"

	["Ore Generation".Overworld."Bohr Generation"]
			#Enable the Generation of Bohr Ore (Default: true).
			generate_bohr = true
			#Set the Temperature of the biome in which the Sapphire Ore should generate(The temperature of the biome is equal and below)(Default: 0.2F)
			#Range: -9.99999999E8 ~ 9.99999999E8
			sapphire_temperature = 1.0
			#Set the Vein Size of the Bohr Ore (Default: 8).
			#Range: 4 ~ 255
			veinsize_bohr = 8
			#Set the Count of the Bohr Ore how much can spawn per Chunk (Default: 1).
			#Range: 1 ~ 255
			count_bohr = 1
			#Set the Min Height of the Bohr Ore (Default: 0).
			#Range: 0 ~ 256
			minheight_bohr = 0
			#Set the Max  Height of the Bohr Ore (Default: 16).
			#Range: 0 ~ 256
			maxheight_bohr = 16